from pathlib import Path
from typing import Protocol, TypedDict, runtime_checkable


class FileMetadata(TypedDict):
    size: int
    last_modified: float
    last_accessed: float


@runtime_checkable
class FileManager(Protocol):
    """Local storage capability consumed by the application service."""

    def save_file(self, content: bytes, file_path: str | Path) -> None: ...
    def file_exists(self, file_path: str | Path) -> bool: ...
    def get_file_metadata(self, file_path: str | Path) -> FileMetadata: ...
    def delete_file(self, file_path: str | Path) -> None: ...
    def copy_file(self, source: str | Path, destination: str | Path) -> None: ...
    def ensure_directory_exists(self, directory_path: str | Path) -> None: ...
    def reserve_directory(self, directory_path: str | Path) -> None: ...
    def reserve_file(self, file_path: str | Path) -> None: ...
    def list_files(
        self,
        directory_path: str | Path,
        extensions: tuple[str, ...] | None = None,
    ) -> list[Path]: ...
    def sanitize_filename(self, filename: str) -> str: ...
