"""Narrow logging capability consumed by EchoFlow application services."""

from typing import Protocol, Self, runtime_checkable


@runtime_checkable
class ILogger(Protocol):
    """Application logging port independent of the concrete logging backend."""

    def debug(self, message: str, **kwargs: object) -> None: ...
    def info(self, message: str, **kwargs: object) -> None: ...
    def warning(self, message: str, **kwargs: object) -> None: ...
    def error(self, message: str, **kwargs: object) -> None: ...
    def bind(self, **kwargs: object) -> Self: ...
